apiVersion: v1
kind: Service
metadata:
  name: ev-data-mgmt-service
spec:
  type: ClusterIP
  selector:
    app: ev-data-mgmt-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
